-- MySQL Script generated by MySQL Workbench
-- Mon Sep 17 11:10:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `Item Number` INT NOT NULL,
  `Item Description` VARCHAR(45) NULL,
  `Cost Per Item` INT NULL,
  `Item Discontinued` VARCHAR(45) NULL,
  `Item Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Item Number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendor` (
  `Vendor Number` INT NOT NULL,
  `vendor description` VARCHAR(45) NULL,
  PRIMARY KEY (`Vendor Number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `idOrders` INT NOT NULL,
  `Reorder` INT NULL,
  `Item Number` INT NULL,
  `Vendor Number` INT NULL,
  `Date of last order` DATETIME NULL,
  PRIMARY KEY (`idOrders`),
  INDEX `Item Number_idx` (`Item Number` ASC),
  INDEX `Vendor Number_idx` (`Vendor Number` ASC),
  CONSTRAINT `Item Number`
    FOREIGN KEY (`Item Number`)
    REFERENCES `mydb`.`Item` (`Item Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Vendor Number`
    FOREIGN KEY (`Vendor Number`)
    REFERENCES `mydb`.`Vendor` (`Vendor Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Locations` (
  `idLocations` INT NOT NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocations`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categories` (
  `idCategories` INT NOT NULL,
  `Categories` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stock Control`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stock Control` (
  `idStock Control` INT NOT NULL,
  `Item Number` INT NULL,
  `Stock Locaiton` INT NULL,
  `Stock Quantity` INT NULL,
  `Stock Category` INT NULL,
  `Total value` INT NULL,
  PRIMARY KEY (`idStock Control`),
  INDEX `Item Number_idx` (`Item Number` ASC),
  INDEX `Stock Location_idx` (`Stock Locaiton` ASC),
  INDEX `Stock Category_idx` (`Stock Category` ASC),
  CONSTRAINT `Item Number`
    FOREIGN KEY (`Item Number`)
    REFERENCES `mydb`.`Item` (`Item Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Stock Location`
    FOREIGN KEY (`Stock Locaiton`)
    REFERENCES `mydb`.`Locations` (`idLocations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Stock Category`
    FOREIGN KEY (`Stock Category`)
    REFERENCES `mydb`.`Categories` (`idCategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
