# Generated by Django 2.2 on 2019-11-07 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20191107_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcontrol',
            name='total_value',
        ),
    ]
